In [10]:
%pip install -r ../../requirements.txt

import pandas as pd

Requirement already satisfied: pandas==2.2.2 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from -r ../../requirements.txt (line 1)) (2.2.2)
Collecting scikit-learn (from -r ../../requirements.txt (line 2))
  Using cached scikit_learn-1.9.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from -r ../../requirements.txt (line 3)) (3.10.8)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from pandas==2.2.2->-r ../../requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from pandas==2.2.2->-r ../../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from pandas==2.2.2->-r ../../requirements.txt (line 1)) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from pandas==2.2.2->-r ../../requirements.txt (line 1)) (2025.3)
Collecting scipy>=1.10.0 (from scikit-learn->-r ../../requirements.txt (line 2))
  Downloading scipy-1.18.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn->-r ../../requirements.txt (line 2))
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn->-r ../../requirements.txt (line 2))
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->-r ../../requirements.txt (line 2))
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (25.0)
Requirement already satisfied: pillow>=8 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from matplotlib->-r ../../requirements.txt (line 3)) (3.3.1)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.5.1/libexec/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2->-r ../../requirements.txt (line 1)) (1.17.0)
Downloading scikit_learn-1.9.0-cp314-cp314-macosx_12_0_arm64.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 19.1 MB/s  0:00:009.3 MB/s eta 0:00:01:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading scipy-1.18.0-cp314-cp314-macosx_14_0_arm64.whl (20.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 22.8 MB/s  0:00:003.4 MB/s eta 0:00:01:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [scikit-learn]0m 4/5 [scikit-learn]
Successfully installed joblib-1.5.3 narwhals-2.24.0 scikit-learn-1.9.0 scipy-1.18.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [114]:
toronto_data = pd.read_csv('../data/toronto_real_estate_public_area.csv')

In [115]:
toronto_data.head(3)

,property_id,period,home_type_bucket,status,last_status,home_type,price,list_price,sold_price,list_date,neighbourhood,latitude,longitude,bedrooms,bedrooms_plus,bathrooms,brokerage,images_count,estimated_area_sqft
0,1,sale,CONDO,ACTIVE,PRICE_CHANGE,CONDO,388000.0,388000.0,NaN,2026-04-12T13:29:08.000Z,Waterfront Communities The Island,43.648879,-79.388044,1.0,NaN,1.0,HC REALTY GROUP INC.,46,350.0
1,2,sale,CONDO,ACTIVE,NEW,CONDO,385000.0,385000.0,NaN,2026-05-28T11:31:44.000Z,Moss Park,43.653313,-79.359882,NaN,NaN,1.0,BAKER REAL ESTATE INCORPORATED,24,350.0
2,3,sale,CONDO,ACTIVE,NEW,CONDO,299000.0,299000.0,NaN,2026-06-09T10:35:34.000Z,Church-Yonge Corridor,43.657375,-79.374087,NaN,NaN,1.0,SUPERSTARS REALTY LTD.,25,350.0

In [116]:
# We'll be using sold_price as the target for this model, and won't be using price or list_price as features.

toronto_data = toronto_data.drop(columns=['property_id', 'period', 'brokerage', 'home_type_bucket', 'price', 'list_price', 'images_count','status'])

In [117]:
toronto_data

,last_status,home_type,sold_price,list_date,neighbourhood,latitude,longitude,bedrooms,bedrooms_plus,bathrooms,estimated_area_sqft
0,PRICE_CHANGE,CONDO,NaN,2026-04-12T13:29:08.000Z,Waterfront Communities The Island,43.648879,-79.388044,1.0,NaN,1.0,350.0
1,NEW,CONDO,NaN,2026-05-28T11:31:44.000Z,Moss Park,43.653313,-79.359882,NaN,NaN,1.0,350.0
2,NEW,CONDO,NaN,2026-06-09T10:35:34.000Z,Church-Yonge Corridor,43.657375,-79.374087,NaN,NaN,1.0,350.0
3,NEW,CONDO,NaN,2026-06-20T09:57:05.000Z,Bay Street Corridor,43.661136,-79.385605,1.0,NaN,1.0,650.0
4,NEW,CONDO,NaN,2026-06-03T21:38:51.000Z,South Riverdale,43.657640,-79.350917,1.0,NaN,1.0,550.0
...,...,...,...,...,...,...,...,...,...,...,...
9699,SOLD,CONDO,555000.0,2024-03-15T16:55:50.000Z,Waterfront Communities C1,43.645958,-79.389873,1.0,1.0,1.0,550.0
9700,SOLD,CONDO,585000.0,2024-05-10T16:13:24.000Z,Little Portugal,43.642018,-79.423509,2.0,NaN,2.0,550.0
9701,SOLD,CONDO,600000.0,2024-05-15T16:08:20.000Z,Clairlea Birchmount,43.716540,-79.284514,2.0,NaN,2.0,950.0
9702,SOLD,CONDO,595000.0,2024-04-01T16:00:47.000Z,Moss Park,43.656969,-79.374122,1.0,1.0,1.0,550.0
9703,SOLD,CONDO,550500.0,2024-05-04T15:54:48.000Z,South Parkdale,43.640144,-79.423917,2.0,NaN,2.0,750.0

In [118]:
tud = toronto_data['sold_price'].isnull().sum()
tud

np.int64(3244)

In [119]:
toronto_data.isnull().sum()

last_status               0
home_type                 0
sold_price             3244
list_date                 0
neighbourhood             1
latitude                  0
longitude                 0
bedrooms                290
bedrooms_plus          5460
bathrooms                50
estimated_area_sqft     162
dtype: int64

In [133]:
toronto_data['locality'].isnull().sum()

np.int64(1)

In [127]:
# Renamed column to locality after normalization

toronto_data['locality'] = (
    toronto_data['neighbourhood']
    .dropna()
    .str.lower()
    .str.replace(r'^[a-z0-9]+ - ', '', regex=True)
    .str.replace(r'[-]', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [132]:
len(toronto_data['locality'].unique())

131

In [123]:
(toronto_data['locality'].value_counts()).sum()

np.int64(9703)